#!/usr/bin/env python3
"""Generate the single source of truth for editorial categories.

Writes two artefacts from the CATEGORIES table below:

1. ``data/categories.toml`` — read by the home, Browse (Atlas), and category
   list templates so the label + blurb for each section live in exactly one
   place (no more triple-duplicated dicts across layouts).
2. ``content/<slug>/_index.md`` — a section front-matter stub per category so
   each category page has a proper ``<title>`` and meta ``description`` (good
   SEO) instead of Hugo's auto-humanised guess.

Idempotent: re-run any time after adding a category. The slug is the content
directory name and the URL of the section page (``/equity/`` etc.).
"""
from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
DATA = ROOT / "data"

# slug -> (human label, one-line blurb). Order here is the canonical order;
# templates re-sort by entry count, so this is just for the data file.
CATEGORIES: list[tuple[str, str, str]] = [
    ("equity", "Equity", "Stock and shareholder-equity instruments — share classes, voting rights, buybacks, employee equity."),
    ("fixed-income", "Fixed income", "Treasury securities, corporate bonds, structured credit, money-market instruments, credit ratings."),
    ("derivatives", "Derivatives", "Options, futures, forwards, swaps — and the Greeks and pricing models that price them."),
    ("funds", "Funds", "Every flavour of pooled vehicle: ETFs, mutual funds, hedge funds, private equity, sovereign-wealth, endowments."),
    ("forex", "Foreign exchange", "Currency pairs, exchange-rate regimes, FX derivatives, intervention, the major reserve currencies."),
    ("commodities", "Commodities", "Metals, energy, agriculture and livestock — the futures curve, contango, storage, indices."),
    ("macro", "Macroeconomics", "Macroeconomic concepts that move markets: output, prices, employment, the business cycle."),
    ("monetary", "Monetary policy", "Central banking and money-supply mechanics — interest rates, QE, aggregates, reserve currencies."),
    ("fiscal", "Fiscal policy", "Government finance — budgets, public debt, sovereign default, taxation at the sovereign level."),
    ("ratios", "Financial ratios", "Valuation, profitability, liquidity, solvency, efficiency and market-risk ratios — when each helps and when it lies."),
    ("accounting", "Accounting", "The three financial statements, GAAP and IFRS, key line items, and the bridges between statements."),
    ("strategies", "Strategies", "Value, growth, momentum, factor and quantitative styles — plus rebalancing, tax-loss harvesting and other tactics."),
    ("risk", "Risk", "Types of risk and how they are measured — VaR, CVaR, expected shortfall, stress testing, hedging."),
    ("behavioral", "Behavioral finance", "Cognitive biases, prospect theory, mental accounting, and market-sentiment phenomena."),
    ("history", "Financial history", "Crises, bubbles, panics and structural shifts — from tulip mania to the COVID crash."),
    ("people", "People & thinkers", "Famous investors, economists and financial thinkers — focused on their ideas and influence."),
    ("regulation", "Regulation", "Securities laws, regulators and regulatory frameworks — Dodd-Frank, MiFID, Basel, KYC."),
    ("corporate", "Corporate finance", "Mergers and acquisitions, takeover defences, leveraged buyouts, governance, dividend and buyback policy."),
    ("personal-finance", "Personal finance", "Household money management — saving, budgeting, retirement vehicles, insurance, credit."),
    ("taxes", "Taxes", "Investor-facing tax concepts: capital gains, qualified dividends, cost basis, tax-advantaged structures."),
    ("real-estate", "Real estate", "Real estate as an asset class and as financing — REITs, mortgages, and the metrics that value property."),
    ("trading", "Trading & execution", "Order types, execution, market microstructure, settlement and clearing, intraday phenomena."),
    ("crypto", "Crypto & DeFi", "Major chains, consensus mechanisms, on-chain instruments, DeFi primitives, custody, exchanges."),
    ("technical-analysis", "Technical analysis", "Chart-based analysis — candlesticks, support and resistance, patterns, indicators, oscillators."),
    ("institutions", "Institutions", "Major financial firms, exchanges, clearing utilities, index providers and rating agencies."),
    ("valuation", "Valuation", "DCF, trading multiples, residual income and real options — the methods and the inputs they need."),
    ("markets", "Markets & structure", "Market structure and venue mechanics — primary vs secondary, exchanges, dark pools, indices."),
]


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_data_file() -> None:
    lines = [
        "# Generated by scripts/gen_category_pages.py — do not edit by hand.",
        "# Single source of truth for editorial-category labels and blurbs.",
        "# Read by layouts/index.html, layouts/_default/atlas.html, and",
        "# layouts/_default/list.html. Re-run the script to regenerate.",
        "",
    ]
    for slug, label, blurb in CATEGORIES:
        lines.append("[[category]]")
        lines.append(f'  slug  = "{toml_escape(slug)}"')
        lines.append(f'  label = "{toml_escape(label)}"')
        lines.append(f'  blurb = "{toml_escape(blurb)}"')
        lines.append("")
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "categories.toml").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DATA / 'categories.toml'} ({len(CATEGORIES)} categories)")


def yaml_escape(s: str) -> str:
    return s.replace('"', '\\"')


def write_section_indexes() -> None:
    written = 0
    for slug, label, blurb in CATEGORIES:
        d = CONTENT / slug
        if not d.is_dir():
            print(f"  !! skip {slug}: content/{slug}/ does not exist")
            continue
        fm = (
            "---\n"
            f'title: "{yaml_escape(label)}"\n'
            f'description: "{yaml_escape(blurb)}"\n'
            "---\n"
        )
        (d / "_index.md").write_text(fm, encoding="utf-8")
        written += 1
    print(f"wrote {written} content/<slug>/_index.md stubs")


if __name__ == "__main__":
    write_data_file()
    write_section_indexes()
