#!/usr/bin/env python3
"""Generate data/learn_links.toml — the wiki -> learn library cross-link map.

Where a wiki entry and a library lesson describe the same concept (same slug),
the wiki entry should point at the lesson as further reading. Google was
crawling ~5.5k /learn/library/** lessons without indexing them, in part
because almost nothing on the site linked to them; the wiki is the largest
link surface we own.

Matching is by exact slug. Slugs that resolve to more than one lesson are
skipped on purpose: the library has genuine internal duplicates (e.g. 30
"glossary" pages, continuous-compounding under two different books) and
picking one arbitrarily would harden a choice the duplicate audit in the
learn repo still has to make. Re-run this once those are merged to pick the
skipped entries up.

Usage:
    python3 scripts/gen_learn_links.py [--sitemap PATH_OR_URL]
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parent.parent
CONTENT = REPO / "content"
OUT = REPO / "data" / "learn_links.toml"

DEFAULT_SITEMAP = "https://pomegra.io/learn/library/sitemap.xml"
# URLs are stored absolute on purpose. hugo.toml sets canonifyURLs = true,
# which rewrites a root-relative "/learn/..." into "/wiki/learn/..." - the
# library lives outside this site, so the baseURL prefix must not be applied.
DEFAULT_ORIGIN = "https://pomegra.io"
SITEMAP_NS = "{http://www.sitemaps.org/schemas/sitemap/0.9}"

# /learn/library/<track>/<course>/<chapter>/<lesson>
LESSON_RE = re.compile(
    r"^/learn/library/(?P<track>[^/]+)/(?P<course>[^/]+)/(?P<chapter>[^/]+)/(?P<slug>[^/]+)$"
)
CHAPTER_PREFIX_RE = re.compile(r"^chapter[-_]?\d+[-_]?")


def humanize(slug: str) -> str:
    """'the-math-gently' -> 'The Math Gently'. Keeps short joining words lower."""
    small = {"a", "an", "and", "as", "at", "for", "in", "of", "on", "or", "the", "to", "vs"}
    words = [w for w in slug.replace("_", "-").split("-") if w]
    out = []
    for i, w in enumerate(words):
        out.append(w if (i and w.lower() in small) else w.capitalize())
    return " ".join(out)


def read_sitemap(src: str) -> str:
    if src.startswith(("http://", "https://")):
        with urllib.request.urlopen(src, timeout=60) as r:  # noqa: S310
            return r.read().decode("utf-8")
    return pathlib.Path(src).read_text(encoding="utf-8")


def lesson_index(xml_text: str) -> dict[str, list[dict[str, str]]]:
    """slug -> [lesson, ...]. Only 6-segment lesson URLs qualify."""
    root = ET.fromstring(xml_text)
    by_slug: dict[str, list[dict[str, str]]] = defaultdict(list)
    for loc in root.iter(f"{SITEMAP_NS}loc"):
        url = (loc.text or "").strip()
        path = re.sub(r"^https?://[^/]+", "", url)
        m = LESSON_RE.match(path)
        if not m:
            continue
        by_slug[m.group("slug")].append(
            {
                "url": path,
                "course": humanize(m.group("course")),
                "chapter": humanize(CHAPTER_PREFIX_RE.sub("", m.group("chapter"))),
            }
        )
    return by_slug


def wiki_slugs() -> set[str]:
    return {
        p.stem
        for p in CONTENT.rglob("*.md")
        if p.stem not in {"_index", "index"}
    }


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sitemap", default=DEFAULT_SITEMAP)
    ap.add_argument("--origin", default=DEFAULT_ORIGIN)
    args = ap.parse_args()

    lessons = lesson_index(read_sitemap(args.sitemap))
    slugs = wiki_slugs()

    matched = sorted(s for s in slugs if s in lessons)
    unique = [s for s in matched if len(lessons[s]) == 1]
    skipped = [s for s in matched if len(lessons[s]) > 1]

    lines = [
        "# Generated by scripts/gen_learn_links.py - do not edit by hand.",
        "# Maps a wiki entry slug to the library lesson covering the same concept.",
        "# Read by layouts/_default/single.html to render the 'Learn more' block.",
        f"# {len(unique)} links; {len(skipped)} ambiguous slugs skipped.",
        "",
    ]
    for s in unique:
        lesson = lessons[s][0]
        lines += [
            "[[link]]",
            f'  slug    = "{toml_escape(s)}"',
            f'  url     = "{toml_escape(args.origin + lesson["url"])}"',
            f'  course  = "{toml_escape(lesson["course"])}"',
            f'  chapter = "{toml_escape(lesson["chapter"])}"',
            "",
        ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(unique)} links, {len(skipped)} ambiguous skipped")
    if skipped:
        print("  ambiguous: " + ", ".join(skipped[:8]) + (" ..." if len(skipped) > 8 else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
